theme: fullwidth
title: Chronos
author: Adam Graham
author_url: https://github.com/adamgraham
github_url: https://github.com/adamgraham/Chronos
copyright: Copyright (c) 2016 Adam Graham
readme: README.md
source_directory: ./Chronos
clean: true
skip_undocumented: true
custom_categories: 
  - name: Chronos
    children: ["Timer", "TimerDelegate", "TimerEvent", "TimerState", "TimerType"]
